version: '3.1'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'postgres'

  backend:
    build: .
    image: spring-sandbox:latest
    depends_on: 
      - postgres
    ports:
      - '5204:5204'
    environment: 
      - DB_HOST=postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5204/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3